backend:
  name: github
  repo: DaliborIlic/ueno-gatsby-starter
media_folder: static/assets
public_folder: assets
collections:
  - name: phone
    label: Phone
    folder: phone
    create: true
    fields:
      - { name: path, label: 'Path (slug) lowercase with dash instead of spaces, e.g. /phones/samsung-s8'}
      - { name: title, label: Title }
      - { name: date, label: Date, widget: date }
      - { name: featuredImage, label: Featured Image, widget: image }      
      - { name: body, label: Body, widget: markdown }