backend:
  name: github
  repo: DaliborIlic/ueno-gatsby-starter
media_folder: static/assets
public_folder: assets
collections:
  - name: work
    label: Work
    folder: work
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: date }
      - { name: featuredImage, label: Featured Image, widget: image }      
      - { name: body, label: Body, widget: markdown }